### ISSUE TITLE
Feature Request: Allow module imports in content scripts

### ISSUE THREAD

**Issue by abeledovictor** [Jonghakseo/chrome-extension-boilerplate-react-vite#160]
I was using a [similar package](https://github.com/lxieyang/chrome-extension-boilerplate-react) for Chrome extension development with react in the past.

That one allows imports in the content script. I think it would be a great feature to add because if not the content script file gets huge, with lots of lines of code and different logic.

Is this something achievable with Vite?

**Comment by govza** [comment]
I'm using the trick actually:
/src/pages/content/index.ts
```js
import("@src/pages/content/Root");
```
and in Root.ts, just doing module imports.

**Comment by PatrykKuniczak** [comment]
@abeledovictor That one is solved or you still looking forward to this update?

**Comment by abeledovictor** [comment]
@PatrykKuniczak I think it is not solved because I cannot use 

`import DefaultImport from 'x'`

or 

`import {NamedImport} from 'y'`

in my content script files.

**Comment by PatrykKuniczak** [comment]
@abeledovictor I will try to reproduce this, and if i have solution i will contact with repo owner for improve this, but repo owner is soo little active.

But i think he want to maintain this repo, cause post some messages last time.

**Comment by Jonghakseo** [comment]
Due to a number of practical issues (career schedule, consulting, personal time), I was not allocating enough physical time to my current project. Fortunately, starting tomorrow, I'll have a long holiday break in Korea, and I'll be spending some of this time with my family before allocating it to repo improvements.

I know I can't realistically address all the issues, but I'll do my best to review them and improve the ones I can :)

If you have any suggestions for issues, please feel free to submit them via PR! I will review them as soon as possible.

**Comment by abeledovictor** [comment]
I do not have the time either. I guess the solution should include adding a rollup plugin like this one @rollup/plugin-commonjs and configuring it to only process the content script file. @PatrykKuniczak

**Comment by abeledovictor** [comment]
> I'm using the trick actually: /src/pages/content/index.ts
> 
> ```js
> import("@src/pages/content/Root");
> ```
> 
> and in Root.ts, just doing module imports.

So, there is only one import that should be done using this syntax? `import("@src/pages/content/Root");` @govza ?

If that is the case, we could change the wording of the comment in `src/pages/content/index.ts`

**From:** 

_Chrome extensions don't support modules in content scripts._


**To:**

_This import is needed only to mount the React Root in the DOM. You can still use module import syntax like this one:

import library from 'x'
import {helperFunction} from 'y'

Here and in any other content file, including ./components/Demo


The logic behind this feature request was that the comment found in `src/pages/content/index.ts` is confusing and made me think that the only way to import files and libs on the whole content script file, was by using this `import("@src/pages/content/Root");` import syntax.

**Comment by PatrykKuniczak** [comment]
@abeledovictor @Jonghakseo 

I find it accidentally when i watching for other solution 😁

https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension

There's workaround for enable, maybe we want to implement STH like that in template, for give for users opportunity to use our import over standard, and works on the same way

**Comment by Jonghakseo** [comment]
> @abeledovictor @Jonghakseo
> 
> I find it accidentally when i watching for other solution 😁
> 
> https://stackoverflow.com/questions/48104433/how-to-import-es6-modules-in-content-script-for-chrome-extension
> 
> There's workaround for enable, maybe we want to implement STH like that in template, for give for users opportunity to use our import over standard, and works on the same way

You're amazing...! I'll take a look right now.

**Comment by Jonghakseo** [comment]
@PatrykKuniczak 

I checked the solution, but there's a problem. We are relying on the rollup's dependency analysis for information about the dependencies we want to pull.

To resolve dependency issues via a dynamic path like the one above, we need to know the dependency information of the files we want to import beforehand and also go through the transpile process.

In my opinion, it would be nice to have more understandable annotations and structure to use @govza's proposed solution.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I don't understand the problem, but if @govza solution work, you can implement it, and this Root could be sth like accumulator for imports, and there users could import necessary thinks, and this Root import should be predefined in template

**Comment by Jonghakseo** [comment]
@PatrykKuniczak 

I agree. I've opened a PR that's a bit more revealing of the use case.

**Comment by PatrykKuniczak** [comment]
@Jonghakseo we can close it i think, after your PR
